import { useState, useEffect } from "react";

const prompts = [
  // ── FREE (15) ──────────────────────────────────────────────────────────────
  { id:1, title:"Legal Contract Risk Analyzer", category:"Legal", tier:"free", description:"Extract risk clauses, flag unusual terms, and score overall contract safety.", tags:["legal","contracts","risk"], uses:4821, rating:4.9, prompt:`You are a senior contract attorney. Analyze the following contract and:\n1. Identify all risk clauses (score 1-10)\n2. Flag non-standard terms\n3. Suggest protective amendments\n4. Output an executive risk summary\n\nContract: [PASTE CONTRACT]` },
  { id:2, title:"Cold Email Generator", category:"Sales", tier:"free", description:"Write high-converting cold emails with psychological triggers.", tags:["sales","email","copywriting"], uses:7643, rating:4.6, prompt:`You are a world-class sales copywriter. Write a cold email that:\n1. Opens with a pattern interrupt\n2. Uses social proof within 2 sentences\n3. Focuses on ONE specific pain point\n4. Has a low-friction CTA\n\nTarget: [COMPANY/PERSON], Pain: [PAIN POINT]` },
  { id:3, title:"SEO Content Brief Generator", category:"Marketing", tier:"free", description:"Create comprehensive content briefs that rank on page 1.", tags:["seo","content","marketing"], uses:5521, rating:4.8, prompt:`You are an SEO strategist at a top agency. Create a content brief:\n1. Primary & secondary keywords (with search intent)\n2. SERP analysis and content gaps\n3. Outline with H2/H3 structure\n4. Word count, readability, and E-E-A-T requirements\n\nTopic: [TOPIC], Domain: [YOUR SITE]` },
  { id:4, title:"Meeting Summary Generator", category:"Productivity", tier:"free", description:"Turn messy meeting notes into structured action items instantly.", tags:["productivity","meetings","notes"], uses:3201, rating:4.7, prompt:`You are an executive assistant. Transform these meeting notes into:\n1. 3-line executive summary\n2. Decisions made (bullet list)\n3. Action items with owners and deadlines\n4. Open questions requiring follow-up\n\nNotes: [PASTE NOTES]` },
  { id:5, title:"Job Description Writer", category:"HR", tier:"free", description:"Write compelling job descriptions that attract top talent.", tags:["hr","recruiting","hiring"], uses:2890, rating:4.5, prompt:`You are a talent acquisition specialist. Write a job description that:\n1. Opens with a compelling mission statement\n2. Lists responsibilities in order of importance\n3. Separates must-haves from nice-to-haves\n4. Includes salary range and growth path\n5. Ends with a motivating call to apply\n\nRole: [ROLE], Company: [COMPANY], Salary: [RANGE]` },
  { id:6, title:"Product Feedback Analyzer", category:"Product", tier:"free", description:"Extract patterns and insights from customer feedback at scale.", tags:["product","feedback","ux"], uses:1987, rating:4.6, prompt:`You are a product manager at a top SaaS company. Analyze this customer feedback and:\n1. Identify top 5 pain points (frequency + severity)\n2. Spot feature requests with highest demand\n3. Detect sentiment trends\n4. Recommend 3 immediate product improvements\n\nFeedback: [PASTE FEEDBACK]` },
  { id:7, title:"Ad Copy Generator", category:"Marketing", tier:"free", description:"Write scroll-stopping ad copy for Facebook, Google, and LinkedIn.", tags:["ads","copywriting","marketing"], uses:4102, rating:4.7, prompt:`You are a performance marketing expert. Write ad copy variants:\n1. Headline A/B/C (under 30 chars each)\n2. Primary text (3 variants — pain, gain, fear)\n3. Call to action (3 options)\n4. Platform-specific adaptations (FB, Google, LinkedIn)\n\nProduct: [PRODUCT], Audience: [TARGET], Goal: [CONVERSION]` },
  { id:8, title:"Bug Report Template", category:"Engineering", tier:"free", description:"Write detailed, reproducible bug reports that developers can act on.", tags:["engineering","bugs","qa"], uses:2341, rating:4.5, prompt:`You are a senior QA engineer. Transform this description into a structured bug report:\n1. Title (concise, specific)\n2. Environment (OS, browser, version)\n3. Steps to reproduce (numbered)\n4. Expected vs actual behavior\n5. Severity and priority\n6. Possible root cause\n\nDescription: [BUG DESCRIPTION]` },
  { id:9, title:"Customer Support Response", category:"Product", tier:"free", description:"Write empathetic, solution-focused customer support responses.", tags:["support","customer","communication"], uses:3876, rating:4.6, prompt:`You are a head of customer success. Write a support response that:\n1. Acknowledges the customer's frustration\n2. Takes ownership (no blame-shifting)\n3. Provides a clear solution or next step\n4. Sets realistic expectations\n5. Closes with genuine care\n\nIssue: [CUSTOMER COMPLAINT]\nContext: [PRODUCT/SITUATION]` },
  { id:10, title:"Weekly Status Report", category:"Productivity", tier:"free", description:"Transform bullet points into polished executive status reports.", tags:["productivity","reporting","communication"], uses:2654, rating:4.5, prompt:`You are an executive communications specialist. Write a weekly status report:\n1. Executive summary (3 sentences max)\n2. Accomplishments this week (impact-focused)\n3. In progress (with % complete)\n4. Blockers and asks\n5. Plan for next week\n\nRaw notes: [PASTE YOUR NOTES]\nAudience: [MANAGER/EXEC TEAM]` },
  { id:11, title:"Salary Negotiation Script", category:"HR", tier:"free", description:"Script a confident salary negotiation conversation with counter-offer strategies.", tags:["hr","negotiation","career"], uses:5234, rating:4.8, prompt:`You are a career coach who has helped 1,000+ people negotiate salaries. Write a negotiation script:\n1. Opening statement (anchor high)\n2. Justification (market data + value)\n3. Response to pushback (3 scenarios)\n4. Counter-offer language\n5. Closing and next steps\n\nRole: [JOB TITLE], Target salary: [AMOUNT], Current offer: [OFFER]` },
  { id:12, title:"Competitor Research Summary", category:"Research", tier:"free", description:"Synthesize competitor research into actionable strategic insights.", tags:["research","competitive","strategy"], uses:2109, rating:4.6, prompt:`You are a competitive intelligence analyst. Summarize this research:\n1. Competitor snapshot (product, pricing, positioning)\n2. Strengths to respect\n3. Weaknesses to exploit\n4. Messaging gaps we can own\n5. Strategic recommendation\n\nResearch: [PASTE RAW RESEARCH]` },
  { id:13, title:"One-Pager Writer", category:"Marketing", tier:"free", description:"Write a crisp one-pager that explains your product to anyone in 60 seconds.", tags:["marketing","sales","communication"], uses:1876, rating:4.7, prompt:`You are a B2B marketing director. Write a one-pager:\n1. Headline (outcome-focused)\n2. Problem statement (2 sentences)\n3. Solution (3 bullet differentiators)\n4. Social proof (metrics or logos)\n5. CTA with contact info\n\nProduct: [DESCRIPTION], Audience: [TARGET], Key metric: [RESULT YOU DELIVER]` },
  { id:14, title:"Sprint Retrospective Facilitator", category:"Product", tier:"free", description:"Run a structured retrospective that surfaces real issues and drives improvement.", tags:["product","agile","team"], uses:1543, rating:4.6, prompt:`You are an agile coach. Facilitate a sprint retrospective:\n1. What went well (celebrate wins)\n2. What didn't go well (be specific, no blame)\n3. Root cause analysis (5 whys for top issue)\n4. Action items with owners (max 3)\n5. Process experiment for next sprint\n\nSprint: [SPRINT #], Team: [TEAM NAME], Notes: [RAW INPUT]` },
  { id:15, title:"Tech Stack Decision Framework", category:"Engineering", tier:"free", description:"Evaluate and decide between technology options using a structured framework.", tags:["engineering","architecture","decision"], uses:1876, rating:4.7, prompt:`You are a CTO advising on technology decisions. Evaluate these options:\n1. Scoring matrix (performance, scalability, DX, cost, community)\n2. Trade-off analysis\n3. Risk assessment\n4. Recommendation with rationale\n5. Migration path if switching later\n\nDecision: [WHAT YOU'RE CHOOSING BETWEEN]\nConstraints: [TEAM SIZE, BUDGET, TIMELINE]` },

  // ── PRO (60) ───────────────────────────────────────────────────────────────
  // Marketing (12)
  { id:16, title:"Email Sequence Automator", category:"Marketing", tier:"pro", description:"Write a 7-email nurture sequence that converts leads to customers.", tags:["email","automation","nurture"], uses:2987, rating:4.9, prompt:`You are a conversion copywriter. Write a 7-email nurture sequence:\nEmail 1: Welcome + quick win (Day 0)\nEmail 2: Problem agitation (Day 2)\nEmail 3: Solution education (Day 4)\nEmail 4: Social proof (Day 7)\nEmail 5: Objection handling (Day 10)\nEmail 6: Urgency/scarcity (Day 14)\nEmail 7: Final offer (Day 16)\n\nProduct: [PRODUCT], Audience: [ICP], Main benefit: [BENEFIT]` },
  { id:17, title:"Brand Voice Guide Creator", category:"Marketing", tier:"pro", description:"Define your brand tone, vocabulary, and communication style.", tags:["brand","copywriting","strategy"], uses:1876, rating:4.8, prompt:`You are a brand strategist. Create a brand voice guide:\n1. Voice adjectives (3-5 words with examples)\n2. Do's and don'ts for communication\n3. Vocabulary: words we use vs avoid\n4. Sample copy in 3 scenarios\n5. Tone variations by context\n\nBrand: [NAME], Audience: [TARGET], Values: [CORE VALUES]` },
  { id:18, title:"Social Media Content Calendar", category:"Marketing", tier:"pro", description:"Create a 30-day content calendar with post ideas and hooks.", tags:["social","content","calendar"], uses:2876, rating:4.7, prompt:`You are a social media strategist. Create a 30-day content calendar:\n1. Content pillars (3-4 themes)\n2. Post frequency per platform\n3. 30 post ideas with hooks\n4. Best posting times\n5. Engagement tactics\n\nBrand: [NAME], Platforms: [LIST], Audience: [TARGET]` },
  { id:19, title:"Press Release Writer", category:"Marketing", tier:"pro", description:"Write a newsworthy press release journalists actually publish.", tags:["pr","press","media"], uses:1234, rating:4.6, prompt:`You are a PR director. Write a press release:\n1. Headline (newsy, not salesy)\n2. Dateline and lead paragraph\n3. Body (inverted pyramid)\n4. Executive quote\n5. Boilerplate\n6. Media contact\n\nAnnouncement: [WHAT], Company: [NAME], Date: [DATE]` },
  { id:20, title:"LinkedIn Profile Optimizer", category:"Marketing", tier:"pro", description:"Rewrite your LinkedIn profile to attract opportunities and clients.", tags:["linkedin","personal brand","b2b"], uses:3201, rating:4.6, prompt:`You are a personal branding expert. Rewrite this LinkedIn profile:\n1. Headline (keyword-rich, value-focused)\n2. About section (hook, story, CTA)\n3. Experience descriptions (achievement-focused)\n4. Skills section optimization\n5. Featured section recommendations\n\nCurrent profile: [PASTE PROFILE], Goal: [WHAT YOU WANT TO ATTRACT]` },
  { id:21, title:"Webinar Script Writer", category:"Marketing", tier:"pro", description:"Write a 45-minute webinar script that educates and converts.", tags:["webinar","content","conversion"], uses:1432, rating:4.7, prompt:`You are a webinar conversion specialist. Write a 45-min script:\n1. Hook (0-3 min): Bold promise + credibility\n2. Teaching (3-35 min): 3 key frameworks\n3. Case study (35-40 min): Proof of results\n4. Offer (40-45 min): Transition + CTA\nInclude: slide notes, transitions, engagement prompts\n\nTopic: [TOPIC], Offer: [WHAT YOU'RE SELLING], Audience: [WHO]` },
  { id:22, title:"Landing Page Copy Writer", category:"Marketing", tier:"pro", description:"Write high-converting landing page copy using proven frameworks.", tags:["landing page","conversion","copywriting"], uses:3456, rating:4.9, prompt:`You are a conversion copywriter. Write landing page copy:\n1. Hero: Headline + subheadline + CTA\n2. Problem block (agitate the pain)\n3. Solution introduction\n4. Features → Benefits (3-5)\n5. Social proof block\n6. FAQ (handle top 5 objections)\n7. Final CTA with urgency\n\nProduct: [DESCRIPTION], Audience: [ICP], Price: [PRICE POINT]` },
  { id:23, title:"YouTube Video Script", category:"Marketing", tier:"pro", description:"Write an engaging YouTube script optimized for watch time and CTR.", tags:["youtube","video","content"], uses:2109, rating:4.7, prompt:`You are a top YouTube strategist. Write a video script:\n1. Hook (0-30s): Pattern interrupt + bold claim\n2. Intro (30s-2min): What they'll learn + why you\n3. Body (3 sections with transitions)\n4. Engagement loop: Ask question at 50% mark\n5. CTA: Subscribe + next video\nInclude: B-roll suggestions, chapter timestamps\n\nTopic: [TOPIC], Target length: [MINUTES], Channel niche: [NICHE]` },
  { id:24, title:"Case Study Writer", category:"Marketing", tier:"pro", description:"Write compelling customer case studies that close deals.", tags:["case study","social proof","b2b"], uses:1654, rating:4.8, prompt:`You are a B2B content strategist. Write a case study:\n1. Headline (specific outcome: X% result in Y timeframe)\n2. Customer background (2 sentences)\n3. The challenge (make it relatable)\n4. The solution (how your product helped)\n5. The results (specific metrics)\n6. Customer quote\n7. Next steps / CTA\n\nCustomer: [COMPANY], Industry: [SECTOR], Result: [KEY METRIC]` },
  { id:25, title:"Newsletter Issue Writer", category:"Marketing", tier:"pro", description:"Write an engaging newsletter issue readers actually open and share.", tags:["newsletter","email","content"], uses:2341, rating:4.7, prompt:`You are a top newsletter writer. Write an issue:\n1. Subject line (5 options, A/B test ready)\n2. Preview text\n3. Opening hook (1 paragraph)\n4. Main story/insight (400-600 words)\n5. Practical takeaway (3 bullets)\n6. Closing line + CTA\n\nTopic: [THIS ISSUE'S FOCUS], Audience: [SUBSCRIBER TYPE], Tone: [VOICE]` },
  { id:26, title:"Product Launch Announcement", category:"Marketing", tier:"pro", description:"Write a multi-channel product launch announcement that drives signups.", tags:["launch","product","announcement"], uses:1876, rating:4.8, prompt:`You are a product marketing manager. Write launch copy for:\n1. Email announcement (to existing list)\n2. Social post (Twitter/LinkedIn)\n3. In-app notification\n4. Blog post opening\n5. Press pitch (2 sentences)\n\nProduct: [NAME + DESCRIPTION], Key differentiator: [WHAT MAKES IT UNIQUE], Audience: [TARGET]` },
  { id:27, title:"Referral Program Designer", category:"Marketing", tier:"pro", description:"Design a referral program with incentives, copy, and tracking mechanics.", tags:["referral","growth","viral"], uses:1321, rating:4.7, prompt:`You are a growth hacker. Design a referral program:\n1. Incentive structure (referrer + referee rewards)\n2. Referral mechanics (link, code, or social share)\n3. Email copy (invite + thank you + reward notification)\n4. Landing page headline and copy\n5. Success metrics to track\n\nProduct: [DESCRIPTION], Current CAC: [AMOUNT], Goal: [% growth]` },

  // Sales (10)
  { id:28, title:"Sales Call Script Builder", category:"Sales", tier:"pro", description:"Build a customized discovery call script with objection handlers.", tags:["sales","script","objections"], uses:3421, rating:4.8, prompt:`You are a VP of Sales. Build a discovery call script:\n1. Opening (build rapport + set agenda)\n2. Discovery questions (pain, impact, urgency)\n3. Demo transition\n4. Objection handlers (price, timing, competition)\n5. Close and next steps\n\nProduct: [PRODUCT], ICP: [IDEAL CUSTOMER]` },
  { id:29, title:"Proposal Writer", category:"Sales", tier:"pro", description:"Write a winning sales proposal that accelerates decisions.", tags:["sales","proposal","b2b"], uses:2109, rating:4.8, prompt:`You are a sales director. Write a winning proposal:\n1. Executive summary (problem + solution + ROI)\n2. Understanding of their situation\n3. Proposed solution (specific to them)\n4. Pricing and packages\n5. ROI calculation\n6. Timeline and next steps\n7. Terms and guarantee\n\nProspect: [COMPANY], Pain: [MAIN PROBLEM], Solution: [YOUR OFFER], Price: [AMOUNT]` },
  { id:30, title:"Follow-Up Email Sequence", category:"Sales", tier:"pro", description:"Write a 5-touch follow-up sequence that re-engages ghosted prospects.", tags:["sales","followup","email"], uses:3654, rating:4.9, prompt:`You are a top sales rep. Write a 5-email follow-up sequence for a ghosted prospect:\nEmail 1 (Day 3): Add value, no ask\nEmail 2 (Day 7): Different angle\nEmail 3 (Day 14): Social proof\nEmail 4 (Day 21): Direct ask\nEmail 5 (Day 30): Break-up email\n\nProduct: [PRODUCT], Last touchpoint: [WHAT HAPPENED], Prospect: [ROLE/COMPANY]` },
  { id:31, title:"Objection Handler Library", category:"Sales", tier:"pro", description:"Build a complete objection handling playbook for your sales team.", tags:["sales","objections","training"], uses:2876, rating:4.8, prompt:`You are a sales trainer. Build an objection handling library:\nFor each objection provide: Acknowledge → Explore → Respond → Confirm\nCover: Price too high, Not the right time, Need to think about it, Using a competitor, Need to check with team, Too complex\n\nProduct: [DESCRIPTION], Price point: [AMOUNT], Main competitors: [LIST]` },
  { id:32, title:"LinkedIn Outreach Message", category:"Sales", tier:"pro", description:"Write personalized LinkedIn connection requests and follow-up messages.", tags:["linkedin","outreach","prospecting"], uses:4231, rating:4.7, prompt:`You are a LinkedIn sales expert. Write an outreach sequence:\n1. Connection request (under 300 chars)\n2. First message after connect (value-first)\n3. Follow-up if no reply (Day 5)\n4. Final attempt (Day 12)\n\nYour role: [TITLE], Prospect: [ROLE/COMPANY], Product: [WHAT YOU SELL], Hook: [SPECIFIC REASON YOU'RE REACHING OUT]` },
  { id:33, title:"Sales Battlecard Creator", category:"Sales", tier:"pro", description:"Build a competitive battlecard for your sales team to win against key rivals.", tags:["sales","competitive","battlecard"], uses:1543, rating:4.8, prompt:`You are a product marketing manager. Create a sales battlecard:\n1. Competitor snapshot (positioning + pricing)\n2. Their strengths (be honest)\n3. Their weaknesses (exploit these)\n4. Our differentiation (3 key points)\n5. Landmine questions (make them discover competitor gaps)\n6. Proof points (metrics, logos, quotes)\n\nOur product: [DESCRIPTION], Competitor: [NAME]` },
  { id:34, title:"QBR Presentation Builder", category:"Sales", tier:"pro", description:"Build a Quarterly Business Review that strengthens customer relationships.", tags:["sales","qbr","customer success"], uses:1234, rating:4.7, prompt:`You are a VP of Customer Success. Build a QBR presentation:\n1. Executive summary (value delivered this quarter)\n2. Key metrics vs. goals\n3. Success stories and ROI proof\n4. Challenges and how we solved them\n5. Roadmap preview\n6. Next quarter goals and plan\n\nCustomer: [COMPANY], Product: [YOURS], Key metrics: [LIST], Quarter: [Q/YEAR]` },
  { id:35, title:"Pricing Page Copy", category:"Sales", tier:"pro", description:"Write conversion-optimized pricing page copy that reduces friction.", tags:["pricing","conversion","saas"], uses:2109, rating:4.8, prompt:`You are a conversion specialist. Write pricing page copy:\n1. Section headline + subheadline\n2. Tier names and one-line descriptions\n3. Feature list copy (benefits not features)\n4. FAQ (handle price objections)\n5. CTA copy for each tier\n6. Guarantee or risk-reversal copy\n\nProduct: [DESCRIPTION], Tiers: [LIST WITH PRICES], Main objection: [BIGGEST HESITATION]` },
  { id:36, title:"Sales Training Module", category:"Sales", tier:"pro", description:"Design a sales training module for onboarding new reps fast.", tags:["sales","training","onboarding"], uses:987, rating:4.6, prompt:`You are a sales enablement manager. Design a training module:\n1. Learning objectives (3-5)\n2. Product knowledge essentials\n3. ICP and persona deep dive\n4. Core messaging and value props\n5. Role-play scenarios (3)\n6. Knowledge check questions\n7. Resources and next steps\n\nProduct: [DESCRIPTION], Rep level: [JUNIOR/MID/SENIOR], Timeline: [DAYS TO RAMP]` },
  { id:37, title:"Win/Loss Analysis Framework", category:"Sales", tier:"pro", description:"Analyze won and lost deals to find patterns and improve win rates.", tags:["sales","analytics","strategy"], uses:876, rating:4.7, prompt:`You are a revenue operations analyst. Analyze these deals:\n1. Win patterns (common factors in won deals)\n2. Loss patterns (common reasons for losses)\n3. Competitive intelligence\n4. Process gaps\n5. Recommendations (top 3 changes)\n\nWon deals: [DETAILS]\nLost deals: [DETAILS]\nTime period: [RANGE]` },

  // Finance (8)
  { id:38, title:"Financial Model Builder", category:"Finance", tier:"pro", description:"Generate 3-statement financial models with scenario analysis.", tags:["finance","modeling","forecasting"], uses:2890, rating:4.7, prompt:`You are a CFO at a top investment bank. Build a 3-statement model:\n1. P&L with 5-year projections\n2. Balance sheet\n3. Cash flow statement\n4. Bull/base/bear scenarios\n\nAssumptions: [INSERT]` },
  { id:39, title:"Investor Pitch Deck Writer", category:"Finance", tier:"pro", description:"Write a compelling pitch deck narrative investors actually read.", tags:["pitch","fundraising","startup"], uses:2341, rating:4.9, prompt:`You are a partner at a top VC firm. Write a pitch deck narrative:\n1. Problem (make them feel the pain)\n2. Solution (show the aha moment)\n3. Market size (TAM/SAM/SOM)\n4. Business model (unit economics)\n5. Traction (metrics that matter)\n6. Team (why you)\n7. Ask (amount + use of funds)\n\nCompany: [NAME], Stage: [STAGE], Sector: [SECTOR]` },
  { id:40, title:"Pricing Strategy Analyzer", category:"Finance", tier:"pro", description:"Analyze and optimize your pricing using proven frameworks.", tags:["pricing","strategy","revenue"], uses:1654, rating:4.8, prompt:`You are a pricing consultant. Analyze this situation:\n1. Van Westendorp price sensitivity analysis\n2. Competitive pricing comparison\n3. Value-based pricing recommendation\n4. Pricing psychology tactics\n5. A/B test roadmap\n\nProduct: [DESCRIPTION], Current price: [PRICE], Competitors: [LIST WITH PRICES]` },
  { id:41, title:"Unit Economics Calculator", category:"Finance", tier:"pro", description:"Model your unit economics to find the path to profitability.", tags:["finance","saas","metrics"], uses:1432, rating:4.8, prompt:`You are a SaaS CFO. Model these unit economics:\n1. CAC breakdown by channel\n2. LTV calculation (ARPU × gross margin ÷ churn)\n3. LTV:CAC ratio analysis\n4. Payback period\n5. Cohort retention impact\n6. Recommendations to improve\n\nARPU: [AMOUNT], Churn: [%], CAC: [AMOUNT], Gross margin: [%]` },
  { id:42, title:"Budget Proposal Writer", category:"Finance", tier:"pro", description:"Write a compelling budget proposal that gets approved.", tags:["finance","budget","planning"], uses:1234, rating:4.6, prompt:`You are a CFO. Write a budget proposal:\n1. Executive summary (ROI first)\n2. Current state and gap\n3. Proposed investment breakdown\n4. Expected return (quantified)\n5. Risk if not approved\n6. Timeline and milestones\n7. Success metrics\n\nDepartment: [TEAM], Request: [AMOUNT], Purpose: [WHAT FOR], Expected ROI: [ESTIMATE]` },
  { id:43, title:"Cash Flow Forecast Builder", category:"Finance", tier:"pro", description:"Build a 12-month cash flow forecast with scenario planning.", tags:["finance","cashflow","planning"], uses:1109, rating:4.7, prompt:`You are a finance director. Build a 12-month cash flow forecast:\n1. Revenue projections (monthly)\n2. Fixed and variable cost breakdown\n3. One-time expenses\n4. Cash runway calculation\n5. Break-even analysis\n6. Optimistic/base/pessimistic scenarios\n\nCurrent MRR: [AMOUNT], Growth rate: [%], Burn rate: [AMOUNT], Cash in bank: [AMOUNT]` },
  { id:44, title:"Investor Update Writer", category:"Finance", tier:"pro", description:"Write a concise, credible investor update that builds confidence.", tags:["fundraising","investor relations","startup"], uses:1876, rating:4.8, prompt:`You are a founder with 10 years of investor relations experience. Write a monthly investor update:\n1. Headline metric (MRR/ARR growth)\n2. Top 3 wins this month\n3. Top 3 challenges + how you're addressing them\n4. Key metrics dashboard\n5. Asks from investors\n6. Next month's priorities\n\nMetrics: [KEY NUMBERS], Wins: [LIST], Challenges: [LIST]` },
  { id:45, title:"M&A Target Evaluation", category:"Finance", tier:"pro", description:"Evaluate an acquisition target with financial and strategic analysis.", tags:["finance","m&a","strategy"], uses:654, rating:4.8, prompt:`You are a corporate development VP. Evaluate this acquisition target:\n1. Strategic fit score (1-10)\n2. Financial summary (revenue, margins, growth)\n3. Synergy opportunities (cost + revenue)\n4. Red flags and risks\n5. Preliminary valuation range\n6. Recommendation: pursue/pass/explore\n\nTarget: [COMPANY], Our company: [DESCRIPTION], Price: [ASKING PRICE]` },

  // Engineering (8)
  { id:46, title:"API Documentation Writer", category:"Engineering", tier:"pro", description:"Write clear, developer-friendly API docs with code examples.", tags:["api","docs","developer"], uses:1432, rating:4.7, prompt:`You are a developer advocate. Document this API endpoint:\n1. Endpoint overview\n2. Authentication requirements\n3. Request parameters (table format)\n4. Response schema with types\n5. Code examples (curl, Python, JavaScript)\n6. Error codes and handling\n7. Rate limiting notes\n\nEndpoint: [ENDPOINT DETAILS]` },
  { id:47, title:"Code Review Checklist Builder", category:"Engineering", tier:"pro", description:"Generate a comprehensive code review checklist for your tech stack.", tags:["code","review","engineering"], uses:1987, rating:4.9, prompt:`You are a principal engineer. Create a code review checklist:\n1. Security vulnerabilities (OWASP top 10)\n2. Performance bottlenecks\n3. Code readability and maintainability\n4. Test coverage requirements\n5. Documentation standards\n6. Stack-specific best practices\n\nStack: [YOUR TECH STACK], Team size: [SIZE]` },
  { id:48, title:"Database Schema Designer", category:"Engineering", tier:"pro", description:"Design optimized database schemas with indexing recommendations.", tags:["database","sql","architecture"], uses:1876, rating:4.8, prompt:`You are a database architect. Design a schema:\n1. Entity relationship diagram (text format)\n2. Table definitions with data types\n3. Primary and foreign keys\n4. Indexing strategy\n5. Normalization analysis\n6. Query performance considerations\n\nUse case: [DESCRIPTION], Scale: [EXPECTED ROWS/REQUESTS]` },
  { id:49, title:"System Design Interview Prep", category:"Engineering", tier:"pro", description:"Prepare a structured system design answer for any technical interview.", tags:["system design","interview","architecture"], uses:3421, rating:4.9, prompt:`You are a FAANG principal engineer. Structure a system design answer:\n1. Clarify requirements (functional + non-functional)\n2. Capacity estimation (users, requests, storage)\n3. High-level architecture diagram (text)\n4. Deep dive on 2-3 components\n5. Trade-offs and alternatives\n6. Bottlenecks and scaling strategy\n\nSystem to design: [e.g. Twitter, Uber, Netflix]` },
  { id:50, title:"Incident Post-Mortem Writer", category:"Engineering", tier:"pro", description:"Write a blameless post-mortem that drives real improvements.", tags:["engineering","incidents","reliability"], uses:1234, rating:4.8, prompt:`You are a site reliability engineer. Write a post-mortem:\n1. Incident summary (what, when, impact)\n2. Timeline of events\n3. Root cause analysis (5 whys)\n4. Contributing factors\n5. Action items (with owners + deadlines)\n6. Detection and response improvements\n\nIncident: [DESCRIPTION]\nDuration: [TIME]\nImpact: [USERS/REVENUE AFFECTED]` },
  { id:51, title:"Technical Roadmap Writer", category:"Engineering", tier:"pro", description:"Write a technical roadmap that aligns engineering with business goals.", tags:["engineering","roadmap","planning"], uses:1109, rating:4.7, prompt:`You are a VP of Engineering. Write a technical roadmap:\n1. Current state assessment\n2. Target state (12-month vision)\n3. Initiatives by quarter (Q1-Q4)\n4. Dependencies and risks\n5. Resource requirements\n6. Success metrics\n\nTeam size: [NUMBER], Key business goals: [LIST], Technical debt areas: [LIST]` },
  { id:52, title:"Security Audit Checklist", category:"Engineering", tier:"pro", description:"Run a comprehensive security audit of your application or infrastructure.", tags:["security","audit","engineering"], uses:987, rating:4.9, prompt:`You are a cybersecurity expert. Create a security audit checklist:\n1. Authentication and authorization\n2. Data encryption (in transit + at rest)\n3. Input validation and SQL injection\n4. API security\n5. Dependency vulnerabilities\n6. Infrastructure and cloud security\n7. Logging and monitoring\n\nStack: [YOUR TECH], Type of app: [WEB/API/MOBILE], Compliance needed: [SOC2/GDPR/HIPAA]` },
  { id:53, title:"Engineering Job Interview Question Bank", category:"Engineering", tier:"pro", description:"Create a structured interview question bank for hiring engineers.", tags:["engineering","hiring","interview"], uses:1432, rating:4.7, prompt:`You are an engineering director. Create an interview question bank:\n1. Technical fundamentals (5 questions)\n2. System design (3 scenarios)\n3. Coding problems (5 with hints)\n4. Behavioral questions (STAR format, 5)\n5. Culture and values fit (5)\n6. Evaluation rubric for each section\n\nRole: [SENIOR/MID/JUNIOR], Stack: [TECHNOLOGIES], Team focus: [FRONTEND/BACKEND/FULLSTACK]` },

  // Legal (8)
  { id:54, title:"NDA Generator", category:"Legal", tier:"pro", description:"Draft a comprehensive NDA tailored to your business situation.", tags:["legal","nda","contracts"], uses:2341, rating:4.7, prompt:`You are a business attorney. Draft an NDA covering:\n1. Definition of confidential information\n2. Obligations of receiving party\n3. Exclusions from confidentiality\n4. Term and termination\n5. Remedies for breach\n6. Governing law\n\nParties: [COMPANY A] and [COMPANY B]\nPurpose: [WHY SHARING INFORMATION]\nDuration: [HOW LONG]` },
  { id:55, title:"Privacy Policy Writer", category:"Legal", tier:"pro", description:"Write a GDPR and CCPA compliant privacy policy for your website or app.", tags:["legal","privacy","compliance"], uses:1987, rating:4.6, prompt:`You are a privacy attorney. Write a privacy policy covering:\n1. What data we collect\n2. How we use it\n3. Who we share it with\n4. User rights (GDPR + CCPA)\n5. Cookie policy\n6. Data retention\n7. Contact and complaints\n\nBusiness: [DESCRIPTION], Users: [WHERE LOCATED], Data collected: [LIST]` },
  { id:56, title:"Terms of Service Writer", category:"Legal", tier:"pro", description:"Write clear, enforceable terms of service for your product.", tags:["legal","terms","saas"], uses:1654, rating:4.6, prompt:`You are a SaaS attorney. Write terms of service covering:\n1. Acceptance of terms\n2. Account registration and security\n3. Acceptable use policy\n4. Payment and refunds\n5. IP and ownership\n6. Limitation of liability\n7. Termination\n8. Dispute resolution\n\nProduct: [DESCRIPTION], Business model: [SUBSCRIPTION/ONE-TIME], Jurisdiction: [COUNTRY/STATE]` },
  { id:57, title:"Employment Contract Reviewer", category:"Legal", tier:"pro", description:"Review an employment contract for unfair clauses and negotiation opportunities.", tags:["legal","employment","contracts"], uses:2109, rating:4.8, prompt:`You are an employment attorney. Review this contract:\n1. Flag non-compete clauses (scope and enforceability)\n2. Identify IP assignment scope\n3. Review termination provisions\n4. Check severance terms\n5. Flag any unusual clauses\n6. List 5 negotiation opportunities\n\nContract: [PASTE CONTRACT]\nRole: [JOB TITLE], State/Country: [LOCATION]` },
  { id:58, title:"Vendor Contract Negotiation Guide", category:"Legal", tier:"pro", description:"Identify leverage points and negotiation strategies for vendor contracts.", tags:["legal","negotiation","procurement"], uses:1234, rating:4.7, prompt:`You are a procurement attorney. Analyze this vendor contract:\n1. Identify unfavorable terms\n2. Suggest alternative language\n3. Rank negotiation priorities (must-have vs nice-to-have)\n4. Identify vendor leverage vs our leverage\n5. Concessions we can offer\n6. Walk-away conditions\n\nContract: [PASTE CONTRACT]\nVendor: [NAME], Annual value: [AMOUNT]` },
  { id:59, title:"Cease and Desist Letter", category:"Legal", tier:"pro", description:"Draft a firm cease and desist letter for IP or contract violations.", tags:["legal","ip","enforcement"], uses:987, rating:4.6, prompt:`You are an attorney. Draft a cease and desist letter:\n1. Identify the infringing party\n2. Describe the violation clearly\n3. Cite the legal basis\n4. State the required action\n5. Set a response deadline\n6. Outline consequences of non-compliance\n\nViolation: [DESCRIBE], Our rights: [IP/CONTRACT], Deadline: [DAYS]` },
  { id:60, title:"Partnership Agreement Drafter", category:"Legal", tier:"pro", description:"Draft a partnership agreement covering all key commercial terms.", tags:["legal","partnership","contracts"], uses:876, rating:4.7, prompt:`You are a commercial attorney. Draft a partnership agreement:\n1. Roles and responsibilities\n2. Revenue sharing structure\n3. IP ownership\n4. Decision-making process\n5. Term and termination\n6. Non-solicitation\n7. Dispute resolution\n\nParties: [COMPANY A + COMPANY B]\nPurpose: [WHAT YOU'RE DOING TOGETHER]\nRevenue split: [%]` },
  { id:61, title:"Refund Policy Writer", category:"Legal", tier:"pro", description:"Write a clear refund policy that protects your business and satisfies customers.", tags:["legal","policy","ecommerce"], uses:987, rating:4.5, prompt:`You are a business attorney. Write a refund policy:\n1. Eligible refund scenarios\n2. Timeframes and conditions\n3. Process for requesting refund\n4. Edge cases (digital products, subscriptions)\n5. Non-refundable items\n\nBusiness type: [TYPE], Products: [DESCRIPTION]` },

  // HR (7)
  { id:62, title:"Performance Review Writer", category:"HR", tier:"pro", description:"Write fair, specific, and actionable performance reviews.", tags:["hr","management","feedback"], uses:1654, rating:4.6, prompt:`You are an experienced people manager. Write a performance review:\n1. Overall assessment\n2. 3 specific achievements with impact\n3. 2 development areas with examples\n4. SMART goals for next period\n5. Motivating forward-looking statement\n\nEmployee: [NAME], Role: [ROLE], Period: [TIMEFRAME], Notes: [YOUR OBSERVATIONS]` },
  { id:63, title:"Interview Question Generator", category:"HR", tier:"pro", description:"Generate role-specific interview questions with evaluation criteria.", tags:["hr","interviewing","hiring"], uses:2341, rating:4.7, prompt:`You are a talent acquisition expert. Generate interview questions:\n1. Technical/skills questions (5)\n2. Behavioral questions using STAR (5)\n3. Culture fit questions (3)\n4. Role-specific scenario questions (3)\n5. Questions to ask candidates (3)\nFor each: include what a strong answer looks like\n\nRole: [JOB TITLE], Must-haves: [SKILLS/EXPERIENCE], Team culture: [DESCRIBE]` },
  { id:64, title:"Compensation Benchmarking Report", category:"HR", tier:"pro", description:"Build a compensation benchmarking analysis for any role.", tags:["hr","compensation","benchmarking"], uses:1109, rating:4.7, prompt:`You are a compensation analyst. Build a benchmarking report:\n1. Market range (P25/P50/P75/P90)\n2. Factors affecting compensation (location, stage, industry)\n3. Total comp breakdown (base, bonus, equity, benefits)\n4. Internal equity analysis\n5. Recommendation for offer range\n\nRole: [JOB TITLE], Location: [CITY/REMOTE], Company stage: [STARTUP/GROWTH/ENTERPRISE]` },
  { id:65, title:"Employee Onboarding Plan", category:"HR", tier:"pro", description:"Design a 90-day onboarding plan that ramps new hires to full productivity.", tags:["hr","onboarding","management"], uses:1432, rating:4.8, prompt:`You are a people operations director. Design a 90-day onboarding plan:\nDay 1-7: Orientation, systems access, culture immersion\nDay 8-30: Role fundamentals, shadow sessions, first deliverable\nDay 31-60: Independent work, cross-functional meetings, feedback\nDay 61-90: Full ownership, performance baseline, 90-day review\n\nRole: [JOB TITLE], Team: [DEPARTMENT], Key tools: [LIST]` },
  { id:66, title:"Employee Engagement Survey", category:"HR", tier:"pro", description:"Design a comprehensive employee engagement survey with analysis framework.", tags:["hr","engagement","culture"], uses:987, rating:4.6, prompt:`You are an organizational psychologist. Design an engagement survey:\n1. 20 questions across 5 dimensions (role clarity, growth, recognition, belonging, manager quality)\n2. Rating scale design\n3. 3 open-ended questions\n4. Analysis framework\n5. Action planning template based on results\n\nCompany size: [EMPLOYEES], Remote/hybrid/office: [SETUP], Last survey: [WHEN]` },
  { id:67, title:"Termination Letter Writer", category:"HR", tier:"pro", description:"Write a legally careful termination letter that is clear and dignified.", tags:["hr","termination","legal"], uses:1234, rating:4.5, prompt:`You are an HR director and employment attorney. Write a termination letter:\n1. Clear statement of employment end\n2. Effective date\n3. Reason (carefully worded)\n4. Final pay and benefits information\n5. Return of company property\n6. Confidentiality reminder\n7. Transition support offered\n\nEmployee: [NAME], Role: [TITLE], Reason: [PERFORMANCE/RESTRUCTURING/MISCONDUCT], Date: [EFFECTIVE DATE]` },
  { id:68, title:"Team Meeting Agenda Builder", category:"HR", tier:"pro", description:"Build focused meeting agendas that respect time and drive outcomes.", tags:["hr","meetings","productivity"], uses:1876, rating:4.6, prompt:`You are an executive coach. Build a meeting agenda:\n1. Objective statement (one sentence)\n2. Pre-read requirements\n3. Timed agenda items (with owner)\n4. Decision points (clearly labeled)\n5. Parking lot section\n6. Action item template\n\nMeeting type: [ALL-HANDS/1:1/STRATEGY/REVIEW]\nDuration: [MINUTES]\nAttendees: [LIST]\nGoal: [WHAT MUST BE DECIDED/DONE]` },

  // Product (7)
  { id:69, title:"Product Roadmap Builder", category:"Product", tier:"pro", description:"Build a prioritized product roadmap using outcome-based planning.", tags:["product","roadmap","planning"], uses:2109, rating:4.8, prompt:`You are a CPO. Build a product roadmap:\n1. North star metric\n2. Strategic bets (3-5 themes)\n3. Prioritized initiatives (using RICE scoring)\n4. Q1-Q4 timeline\n5. Dependencies and risks\n6. What you're NOT doing (and why)\n\nProduct: [DESCRIPTION], Stage: [STAGE], Team size: [ENGINEERS], Business goal: [TARGET]` },
  { id:70, title:"User Story Generator", category:"Product", tier:"pro", description:"Convert feature ideas into well-structured user stories with acceptance criteria.", tags:["product","agile","stories"], uses:2341, rating:4.8, prompt:`You are a senior PM. Convert this feature idea:\n1. User story (As a... I want... So that...)\n2. 5-7 acceptance criteria (Given/When/Then)\n3. Edge cases to consider\n4. Definition of done\n5. Story point estimate\n\nFeature idea: [DESCRIPTION], User type: [WHO]` },
  { id:71, title:"OKR Framework Builder", category:"Product", tier:"pro", description:"Design quarterly OKRs aligned to company strategy.", tags:["okr","strategy","planning"], uses:1876, rating:4.7, prompt:`You are a strategy consultant. Design a quarterly OKR framework:\n1. 3 company-level Objectives\n2. 3-5 Key Results per Objective\n3. Cascade to team level\n4. Leading vs lagging indicators\n5. Check-in cadence\n\nCompany stage: [STAGE], Priority: [TOP PRIORITY], Team size: [SIZE]` },
  { id:72, title:"Customer Onboarding Flow", category:"Product", tier:"pro", description:"Design a frictionless onboarding experience that reduces churn.", tags:["onboarding","product","retention"], uses:1543, rating:4.7, prompt:`You are a growth PM. Design a customer onboarding flow:\nDay 0: First value moment (aha moment)\nDay 1-3: Habit formation\nDay 7: Engagement checkpoint\nDay 14: Expansion opportunity\nDay 30: Advocacy trigger\n\nProduct: [DESCRIPTION], Key action: [ACTIVATION EVENT]` },
  { id:73, title:"A/B Test Design Framework", category:"Product", tier:"pro", description:"Design statistically valid A/B tests with clear hypotheses and success metrics.", tags:["product","testing","growth"], uses:1234, rating:4.8, prompt:`You are a growth scientist. Design an A/B test:\n1. Hypothesis (If X then Y because Z)\n2. Control vs variant description\n3. Primary and secondary metrics\n4. Sample size calculation\n5. Test duration\n6. Decision criteria (what counts as a win)\n7. Risks and confounders\n\nWhat you want to test: [CHANGE], Current conversion rate: [%], Traffic: [DAILY VISITORS]` },
  { id:74, title:"Feature Specification Writer", category:"Product", tier:"pro", description:"Write a complete feature specification that gives engineering everything they need.", tags:["product","specs","engineering"], uses:1543, rating:4.7, prompt:`You are a senior PM. Write a feature specification:\n1. Problem statement and context\n2. Goals and non-goals\n3. User stories\n4. Functional requirements\n5. Non-functional requirements\n6. UI/UX notes\n7. Analytics requirements\n8. Open questions\n\nFeature: [DESCRIPTION], Users: [WHO], Priority: [P0/P1/P2]` },
  { id:75, title:"Churn Analysis Framework", category:"Product", tier:"pro", description:"Analyze churn data to find patterns and build a retention playbook.", tags:["product","churn","retention"], uses:1109, rating:4.8, prompt:`You are a product analytics expert. Analyze churn:\n1. Churn rate segmentation (plan, cohort, geography)\n2. Behavioral signals before churn\n3. Exit survey theme analysis\n4. Intervention opportunities by segment\n5. Retention playbook (early, mid, late signals)\n6. Metrics to monitor weekly\n\nChurn data: [PASTE OR DESCRIBE]\nProduct: [DESCRIPTION], Current churn: [%]` },

  // Research (5)
  { id:76, title:"Market Research Synthesizer", category:"Research", tier:"pro", description:"Turn raw market data into strategic insights with competitor mapping.", tags:["research","strategy","market"], uses:3102, rating:4.8, prompt:`Act as a McKinsey analyst. Given the following data:\n1. Build a competitive landscape map\n2. Identify whitespace opportunities\n3. Model TAM/SAM/SOM\n4. Recommend top 3 positioning strategies\n\nData: [INSERT DATA]` },
  { id:77, title:"Competitive Analysis Framework", category:"Research", tier:"pro", description:"Build a comprehensive competitor analysis with strategic recommendations.", tags:["competitive","strategy","research"], uses:2156, rating:4.7, prompt:`You are a strategy consultant. Analyze these competitors:\n1. Feature comparison matrix\n2. Pricing and packaging comparison\n3. Positioning and messaging analysis\n4. Strengths and vulnerabilities\n5. Strategic opportunities\n\nOur product: [DESCRIPTION], Competitors: [LIST]` },
  { id:78, title:"Customer Interview Guide", category:"Research", tier:"pro", description:"Design a customer discovery interview guide that uncovers real insights.", tags:["research","customer","discovery"], uses:1654, rating:4.8, prompt:`You are a UX researcher. Design a customer interview guide:\n1. Screener questions (qualify the interviewee)\n2. Warm-up questions\n3. Core discovery questions (open-ended, no leading)\n4. Problem exploration probes\n5. Solution feedback questions\n6. Closing and referral ask\nInclude: facilitation tips and what to listen for\n\nResearch goal: [WHAT YOU WANT TO LEARN], Product: [DESCRIPTION]` },
  { id:79, title:"Survey Design Framework", category:"Research", tier:"pro", description:"Design surveys that get high response rates and actionable data.", tags:["research","survey","data"], uses:1234, rating:4.6, prompt:`You are a research methodologist. Design a survey:\n1. Question sequence (funnel from broad to specific)\n2. Question types (NPS, Likert, open-ended, multiple choice)\n3. Bias-reducing language review\n4. Skip logic recommendations\n5. Incentive strategy\n6. Analysis plan\n\nResearch goal: [WHAT YOU WANT TO KNOW], Audience: [WHO], Length target: [MINUTES]` },
  { id:80, title:"Industry Report Analyzer", category:"Research", tier:"pro", description:"Extract and synthesize key insights from long industry reports.", tags:["research","analysis","strategy"], uses:1432, rating:4.7, prompt:`You are a strategic analyst. Analyze this industry report:\n1. 5 most important findings\n2. Trends that affect our business\n3. Opportunities to act on\n4. Threats to monitor\n5. Data points worth citing in sales/marketing\n6. Questions the report raises but doesn't answer\n\nReport: [PASTE OR SUMMARIZE], Our business: [DESCRIPTION]` },

  // ── ENTERPRISE (25) ────────────────────────────────────────────────────────
  { id:81, title:"Technical Architecture Reviewer", category:"Engineering", tier:"enterprise", description:"Review system designs for scalability, security, and cost efficiency.", tags:["engineering","architecture","devops"], uses:1204, rating:5.0, prompt:`As a Principal Engineer at FAANG, review this architecture:\n1. Identify single points of failure\n2. Project costs at 10x scale\n3. Flag security vulnerabilities\n4. Suggest specific optimizations with trade-offs\n\nArchitecture: [DIAGRAM/DESCRIPTION]` },
  { id:82, title:"M&A Due Diligence Checklist", category:"Legal", tier:"enterprise", description:"Generate a comprehensive due diligence checklist for M&A transactions.", tags:["legal","m&a","finance"], uses:432, rating:5.0, prompt:`You are an M&A attorney. Generate a due diligence checklist:\n1. Corporate structure and governance\n2. Financial statements and projections\n3. IP audit\n4. Employment and benefits review\n5. Litigation and regulatory review\n6. Customer and supplier contracts\n7. Technology and cybersecurity\n\nDeal type: [TYPE], Target: [INDUSTRY], Deal size: [RANGE]` },
  { id:83, title:"Enterprise Sales Playbook", category:"Sales", tier:"enterprise", description:"Build a complete enterprise sales playbook for complex B2B deals.", tags:["enterprise","sales","b2b"], uses:654, rating:4.9, prompt:`You are a CRO who has closed $100M+ in enterprise deals. Build a sales playbook:\n1. Ideal customer profile\n2. Multi-stakeholder mapping\n3. Discovery framework (MEDDIC)\n4. Proposal and pricing strategy\n5. Legal/procurement navigation\n6. Negotiation tactics\n7. QBR framework\n\nProduct: [DESCRIPTION], ACV target: [AMOUNT]` },
  { id:84, title:"Board Presentation Builder", category:"Finance", tier:"enterprise", description:"Structure board-level presentations that drive decisions.", tags:["board","executive","presentation"], uses:321, rating:5.0, prompt:`You are a CFO presenting to a board. Structure this presentation:\n1. Executive summary (decisions needed)\n2. Business performance vs. plan\n3. Key risks and mitigation\n4. Strategic initiatives update\n5. Financial projections\n6. Resource requests with ROI\n\nPeriod: [Q/YEAR], Key messages: [WHAT YOU NEED APPROVED], Data: [METRICS]` },
  { id:85, title:"Regulatory Compliance Analyzer", category:"Legal", tier:"enterprise", description:"Analyze business operations for regulatory compliance gaps.", tags:["compliance","legal","regulatory"], uses:543, rating:4.9, prompt:`You are a compliance officer at a Fortune 500. Analyze for compliance:\n1. Applicable regulations (GDPR, CCPA, SOC2, HIPAA)\n2. Current gaps vs. requirements\n3. Risk severity matrix\n4. Remediation roadmap\n5. Ongoing monitoring requirements\n\nBusiness type: [TYPE], Regions: [LOCATIONS], Data handled: [DESCRIPTION]` },
  { id:86, title:"Workforce Planning Model", category:"HR", tier:"enterprise", description:"Model headcount needs, costs, and hiring timelines for scale.", tags:["hr","workforce","planning"], uses:432, rating:4.8, prompt:`You are a Chief People Officer. Build a workforce plan:\n1. Current vs. target org structure\n2. Headcount requirements by quarter\n3. Fully-loaded cost model per role\n4. Hiring timeline and bottlenecks\n5. Build vs. buy vs. partner decisions\n6. Attrition risk assessment\n\nCompany stage: [STAGE], Growth target: [%], Budget: [AMOUNT]` },
  { id:87, title:"Data Room Preparation Guide", category:"Finance", tier:"enterprise", description:"Prepare a VC-ready data room that accelerates due diligence.", tags:["fundraising","data room","vc"], uses:876, rating:5.0, prompt:`You are a founder who has raised $50M+. Prepare a data room:\n1. Document checklist (categorized)\n2. Financial model requirements\n3. Legal documents to gather\n4. Metrics dashboard template\n5. Common investor questions to pre-answer\n6. Red flags to address proactively\n\nStage: [SERIES], Sector: [INDUSTRY], ARR: [AMOUNT]` },
  { id:88, title:"Crisis Communication Plan", category:"Marketing", tier:"enterprise", description:"Build a crisis communication playbook for PR emergencies.", tags:["crisis","pr","communications"], uses:543, rating:4.9, prompt:`You are a crisis communications expert. Build a response plan:\n1. Crisis severity matrix (P0-P3)\n2. Response team and decision tree\n3. First 24-hour playbook\n4. Holding statements by scenario\n5. Stakeholder communication order\n6. Media response protocol\n7. Post-crisis review\n\nCompany: [TYPE], Potential scenarios: [LIST]` },
  { id:89, title:"SLA Framework Designer", category:"Engineering", tier:"enterprise", description:"Design enterprise-grade SLAs with monitoring and escalation procedures.", tags:["sla","enterprise","operations"], uses:432, rating:4.8, prompt:`You are a VP of Engineering. Design an SLA framework:\n1. Service tier definitions (Platinum/Gold/Silver)\n2. Uptime commitments and measurement\n3. Response and resolution time matrix\n4. Escalation procedures\n5. Credit/penalty structure\n6. Reporting and review cadence\n\nProduct type: [SAAS/API], Enterprise clients: [COUNT]` },
  { id:90, title:"Executive Compensation Designer", category:"HR", tier:"enterprise", description:"Design competitive executive compensation packages with equity strategy.", tags:["compensation","executive","equity"], uses:321, rating:4.9, prompt:`You are a compensation consultant. Design an executive package:\n1. Base salary benchmarking\n2. Annual bonus structure\n3. Equity plan (options vs RSUs)\n4. Benefits and perquisites\n5. Change-of-control provisions\n6. Clawback policies\n\nRole: [TITLE], Stage: [SERIES], Location: [CITY], Budget: [RANGE]` },
  { id:91, title:"Corporate Strategy Framework", category:"Research", tier:"enterprise", description:"Build a 3-year corporate strategy using proven consulting frameworks.", tags:["strategy","corporate","planning"], uses:432, rating:5.0, prompt:`You are a McKinsey partner. Build a 3-year corporate strategy:\n1. Current position analysis (SWOT + Porter's Five Forces)\n2. Market opportunity sizing\n3. Strategic options (3 scenarios)\n4. Recommended strategy with rationale\n5. Capability gaps to address\n6. 100-day execution plan\n\nCompany: [DESCRIPTION], Revenue: [CURRENT], Goal: [3-YEAR TARGET]` },
  { id:92, title:"IPO Readiness Assessment", category:"Finance", tier:"enterprise", description:"Assess your company's readiness for an IPO with a gap analysis.", tags:["finance","ipo","public markets"], uses:234, rating:5.0, prompt:`You are a CFO who has taken 3 companies public. Assess IPO readiness:\n1. Financial reporting readiness (audit history, GAAP compliance)\n2. Corporate governance requirements\n3. Management team completeness\n4. Legal and compliance gaps\n5. IR and communications readiness\n6. Timeline and sequencing recommendation\n\nCompany: [DESCRIPTION], ARR: [AMOUNT], Growth rate: [%], Target IPO date: [TIMEFRAME]` },
  { id:93, title:"Enterprise Security Policy", category:"Engineering", tier:"enterprise", description:"Write a comprehensive information security policy for enterprise compliance.", tags:["security","enterprise","compliance"], uses:321, rating:4.9, prompt:`You are a CISO. Write an information security policy covering:\n1. Access control and IAM\n2. Data classification and handling\n3. Acceptable use policy\n4. Incident response procedure\n5. Vendor security requirements\n6. Employee security training\n7. Audit and compliance requirements\n\nIndustry: [SECTOR], Compliance required: [SOC2/ISO27001/HIPAA], Company size: [EMPLOYEES]` },
  { id:94, title:"Organizational Design Blueprint", category:"HR", tier:"enterprise", description:"Design an optimal org structure for your growth stage and strategy.", tags:["hr","org design","leadership"], uses:321, rating:4.9, prompt:`You are an organizational design consultant. Design an org structure:\n1. Current state assessment\n2. Design principles for this stage\n3. Proposed structure (functional/divisional/matrix)\n4. Spans and layers recommendation\n5. Key role definitions\n6. Transition plan\n\nCompany size: [EMPLOYEES], Stage: [SERIES], Strategy: [GROWTH/EFFICIENCY/BOTH], Challenges: [CURRENT PAIN POINTS]` },
  { id:95, title:"Global Expansion Playbook", category:"Research", tier:"enterprise", description:"Build a market entry playbook for expanding into new geographies.", tags:["strategy","expansion","global"], uses:432, rating:4.9, prompt:`You are a global expansion consultant. Build a market entry playbook:\n1. Market attractiveness scoring (TAM, competition, regulatory)\n2. Entry strategy options (direct, partnership, acquisition)\n3. Go-to-market plan\n4. Legal and compliance requirements\n5. Hiring and team structure\n6. Financial model and milestones\n\nCompany: [DESCRIPTION], Target market: [COUNTRY/REGION], Resources: [BUDGET + TEAM]` },
  { id:96, title:"Acquisition Integration Plan", category:"Finance", tier:"enterprise", description:"Build a 100-day post-acquisition integration plan.", tags:["m&a","integration","operations"], uses:234, rating:5.0, prompt:`You are a post-merger integration expert. Build a 100-day plan:\nDay 1-10: Stabilization and communication\nDay 11-30: Assessment and quick wins\nDay 31-60: Integration workstreams (HR, tech, finance, go-to-market)\nDay 61-100: Culture integration and synergy realization\n\nAcquired company: [DESCRIPTION], Acquiring company: [DESCRIPTION], Synergy target: [AMOUNT]` },
  { id:97, title:"Customer Success Playbook", category:"Sales", tier:"enterprise", description:"Build a customer success playbook for reducing churn and driving expansion.", tags:["customer success","enterprise","retention"], uses:543, rating:4.9, prompt:`You are a VP of Customer Success. Build a CS playbook:\n1. Customer health scoring model\n2. Onboarding journey (enterprise)\n3. EBR/QBR framework\n4. Risk identification and save playbook\n5. Expansion and upsell triggers\n6. Renewal process\n\nProduct: [DESCRIPTION], Avg contract: [ACV], Customer size: [EMPLOYEES AT CUSTOMER]` },
  { id:98, title:"Data Governance Framework", category:"Engineering", tier:"enterprise", description:"Build a data governance framework for enterprise data management.", tags:["data","governance","enterprise"], uses:321, rating:4.9, prompt:`You are a Chief Data Officer. Build a data governance framework:\n1. Data ownership and stewardship model\n2. Data catalog and lineage\n3. Data quality standards\n4. Access and privacy controls\n5. Retention and archival policy\n6. Compliance mapping (GDPR, CCPA)\n\nCompany: [DESCRIPTION], Data volume: [SCALE], Team: [DATA TEAM SIZE]` },
  { id:99, title:"Investor Relations Strategy", category:"Finance", tier:"enterprise", description:"Build a comprehensive IR strategy for public or pre-IPO companies.", tags:["finance","investor relations","public markets"], uses:234, rating:5.0, prompt:`You are a Head of Investor Relations. Build an IR strategy:\n1. Investor targeting (type, size, geography)\n2. Equity story and key messages\n3. Earnings call preparation\n4. Analyst relations plan\n5. Crisis IR playbook\n6. Roadshow strategy\n\nCompany: [DESCRIPTION], Stage: [PUBLIC/PRE-IPO], Market cap/valuation: [AMOUNT]` },
  { id:100, title:"Supply Chain Risk Assessment", category:"Research", tier:"enterprise", description:"Assess and mitigate supply chain risks across your vendor network.", tags:["operations","risk","enterprise"], uses:321, rating:4.9, prompt:`You are a supply chain risk consultant. Assess supply chain risks:\n1. Vendor concentration risk\n2. Geographic risk mapping\n3. Financial health of key suppliers\n4. Single points of failure\n5. Mitigation strategies per risk\n6. Contingency playbook\n\nIndustry: [SECTOR], Key suppliers: [LIST], Revenue at risk: [AMOUNT]` },
];

const categories = ["All","Legal","Research","Finance","Sales","Engineering","Marketing","HR","Productivity","Product"];
const tiers = ["All","free","pro","enterprise"];
const tierColors = {
  free:       { bg:"#00ff9020", border:"#00ff90", text:"#00ff90" },
  pro:        { bg:"#00b4ff20", border:"#00b4ff", text:"#00b4ff" },
  enterprise: { bg:"#ff6b3520", border:"#ff6b35", text:"#ff6b35" },
};
const categoryIcons = { Legal:"⚖", Research:"◎", Finance:"◈", Sales:"◆", Engineering:"⬡", Marketing:"◉", HR:"◫", Productivity:"◧", Product:"◩", All:"◌" };
const TIER_RANK = { free:0, pro:1, enterprise:2 };
const GUMROAD_PRODUCTS = { pro: "chzRZ6SFQGnMvtSjPmcGhw==", enterprise: "Us5Cg7acnoXQb3yXC1b0xg==" };

async function verifyLicenseKey(key) {
  for (const [tier, productId] of Object.entries(GUMROAD_PRODUCTS)) {
    try {
      const res = await fetch("https://api.gumroad.com/v2/licenses/verify", {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: `product_id=${productId}&license_key=${encodeURIComponent(key)}`,
      });
      const data = await res.json();
      if (data.success) return { valid: true, tier };
    } catch(_) {}
  }
  return { valid: false };
}

function GlitchText({ text }) {
  const [g, setG] = useState(false);
  useEffect(() => { const iv = setInterval(() => { setG(true); setTimeout(() => setG(false), 150); }, 3000+Math.random()*2000); return () => clearInterval(iv); }, []);
  return <span style={{ position:"relative", display:"inline-block" }}>{text}{g && <><span style={{ position:"absolute", top:0, left:"2px", color:"#ff003c", clipPath:"polygon(0 30%,100% 30%,100% 50%,0 50%)", opacity:0.8 }}>{text}</span><span style={{ position:"absolute", top:0, left:"-2px", color:"#00ffff", clipPath:"polygon(0 60%,100% 60%,100% 80%,0 80%)", opacity:0.8 }}>{text}</span></>}</span>;
}

function SaveButton() {
  const [saved, setSaved] = useState(false);
  return <button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2000); }} style={{ padding:"12px 20px", background:saved?"#00ff9015":"none", border:`1px solid ${saved?"#00ff90":"#2a3545"}`, color:saved?"#00ff90":"#6677aa", borderRadius:"6px", fontFamily:"'Space Mono',monospace", fontSize:"11px", cursor:"pointer", transition:"all 0.2s", whiteSpace:"nowrap" }}>{saved?"✓ SAVED":"♡ SAVE"}</button>;
}

function LockOverlay({ tier, onUnlock }) {
  const tc = tierColors[tier];
  return <div style={{ position:"absolute", inset:0, borderRadius:"8px", background:"rgba(3,5,8,0.88)", backdropFilter:"blur(3px)", display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", gap:"10px", zIndex:10 }}><div style={{ fontSize:"28px" }}>🔒</div><div style={{ fontFamily:"'Space Mono',monospace", fontSize:"10px", color:tc.text, letterSpacing:"0.12em", textTransform:"uppercase" }}>{tier} prompt</div><button onClick={onUnlock} style={{ background:`${tc.border}18`, border:`1px solid ${tc.border}`, color:tc.text, padding:"7px 16px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"10px", cursor:"pointer" }}>UNLOCK →</button></div>;
}

function PromptCard({ prompt, userTier, onClick, onUnlock }) {
  const [hovered, setHovered] = useState(false);
  const tier = tierColors[prompt.tier];
  const locked = TIER_RANK[userTier] < TIER_RANK[prompt.tier];
  return (
    <div onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)} onClick={() => !locked && onClick(prompt)} style={{ background:hovered&&!locked?"#0d1117":"#080c10", border:`1px solid ${hovered&&!locked?tier.border:"#1a2030"}`, borderRadius:"8px", padding:"20px", cursor:locked?"default":"pointer", transition:"all 0.2s ease", transform:hovered&&!locked?"translateY(-3px)":"none", boxShadow:hovered&&!locked?`0 8px 32px ${tier.border}22`:"none", position:"relative", overflow:"hidden" }}>
      {locked && <LockOverlay tier={prompt.tier} onUnlock={onUnlock} />}
      {hovered && !locked && <div style={{ position:"absolute", top:0, left:0, right:0, height:"1px", background:`linear-gradient(90deg,transparent,${tier.border},transparent)` }} />}
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:"12px" }}>
        <span style={{ fontSize:"22px" }}>{categoryIcons[prompt.category]||"◌"}</span>
        <span style={{ fontSize:"10px", fontFamily:"'Space Mono',monospace", padding:"3px 8px", borderRadius:"2px", background:tier.bg, border:`1px solid ${tier.border}`, color:tier.text, textTransform:"uppercase", letterSpacing:"0.1em" }}>{prompt.tier}</span>
      </div>
      <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"15px", fontWeight:"700", color:"#e8eaf0", marginBottom:"8px", lineHeight:1.3 }}>{prompt.title}</div>
      <div style={{ fontSize:"12px", color:"#556", lineHeight:1.5, marginBottom:"14px" }}>{prompt.description}</div>
      <div style={{ display:"flex", gap:"6px", flexWrap:"wrap", marginBottom:"14px" }}>
        {prompt.tags.map(t => <span key={t} style={{ fontSize:"10px", fontFamily:"'Space Mono',monospace", color:"#445", padding:"2px 6px", border:"1px solid #1e2535", borderRadius:"2px" }}>#{t}</span>)}
      </div>
      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
        <span style={{ fontSize:"11px", color:"#445", fontFamily:"'Space Mono',monospace" }}>{prompt.uses.toLocaleString()} uses</span>
        <span style={{ fontSize:"12px", color:"#ffd700" }}>{"★".repeat(Math.floor(prompt.rating))} {prompt.rating}</span>
      </div>
    </div>
  );
}

function Modal({ prompt, onClose }) {
  const [copied, setCopied] = useState(false);
  if (!prompt) return null;
  const tier = tierColors[prompt.tier];
  return (
    <div onClick={onClose} style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.85)", display:"flex", alignItems:"center", justifyContent:"center", zIndex:1000, padding:"20px", backdropFilter:"blur(4px)" }}>
      <div onClick={e => e.stopPropagation()} style={{ background:"#080c10", border:`1px solid ${tier.border}`, borderRadius:"12px", padding:"32px", maxWidth:"640px", width:"100%", boxShadow:`0 0 60px ${tier.border}33`, position:"relative" }}>
        <div style={{ position:"absolute", top:0, left:0, right:0, height:"2px", background:`linear-gradient(90deg,transparent,${tier.border},transparent)`, borderRadius:"12px 12px 0 0" }} />
        <div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:"20px" }}>
          <div><div style={{ fontSize:"11px", color:tier.text, fontFamily:"'Space Mono',monospace", marginBottom:"8px", letterSpacing:"0.1em" }}>{prompt.category.toUpperCase()} / {prompt.tier.toUpperCase()}</div><div style={{ fontSize:"20px", fontFamily:"'Syne',sans-serif", fontWeight:"800", color:"#e8eaf0" }}>{prompt.title}</div></div>
          <button onClick={onClose} style={{ background:"none", border:"1px solid #1e2535", color:"#556", cursor:"pointer", borderRadius:"4px", width:"32px", height:"32px", fontSize:"18px", display:"flex", alignItems:"center", justifyContent:"center" }}>×</button>
        </div>
        <div style={{ background:"#030508", border:"1px solid #1a2030", borderRadius:"6px", padding:"20px", marginBottom:"20px", fontFamily:"'Space Mono',monospace", fontSize:"12px", color:"#8899bb", lineHeight:"1.8", whiteSpace:"pre-wrap", maxHeight:"240px", overflowY:"auto" }}>{prompt.prompt}</div>
        <div style={{ display:"flex", gap:"10px" }}>
          <button onClick={() => { navigator.clipboard.writeText(prompt.prompt); setCopied(true); setTimeout(() => setCopied(false), 2000); }} style={{ flex:1, background:copied?"#00ff9015":`${tier.border}15`, border:`1px solid ${copied?"#00ff90":tier.border}`, color:copied?"#00ff90":tier.text, padding:"12px", borderRadius:"6px", fontFamily:"'Space Mono',monospace", fontSize:"12px", cursor:"pointer", letterSpacing:"0.05em", transition:"all 0.2s" }}>{copied?"✓ COPIED":"◻ COPY PROMPT"}</button>
          <SaveButton />
        </div>
      </div>
    </div>
  );
}

function LicenseModal({ onClose, onVerified }) {
  const [key, setKey] = useState("");
  const [status, setStatus] = useState("idle");
  const handleVerify = async () => {
    if (!key.trim()) return;
    setStatus("loading");
    const result = await verifyLicenseKey(key.trim());
    if (result.valid) { localStorage.setItem("pv_license_key", key.trim()); localStorage.setItem("pv_tier", result.tier); onVerified(result.tier); onClose(); }
    else setStatus("error");
  };
  return (
    <div onClick={onClose} style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.9)", display:"flex", alignItems:"center", justifyContent:"center", zIndex:2000, padding:"20px", backdropFilter:"blur(6px)" }}>
      <div onClick={e => e.stopPropagation()} style={{ background:"#080c10", border:"1px solid #00b4ff", borderRadius:"12px", padding:"36px", maxWidth:"480px", width:"100%", position:"relative" }}>
        <div style={{ position:"absolute", top:0, left:0, right:0, height:"2px", background:"linear-gradient(90deg,transparent,#00b4ff,#00ff90,transparent)", borderRadius:"12px 12px 0 0" }} />
        <div style={{ fontSize:"11px", color:"#00b4ff", fontFamily:"'Space Mono',monospace", letterSpacing:"0.2em", marginBottom:"12px" }}>// UNLOCK LIBRARY</div>
        <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"20px", fontWeight:"900", color:"#e8eaf0", marginBottom:"8px" }}>Enter your unlock code</div>
        <div style={{ fontSize:"12px", color:"#556", marginBottom:"24px", lineHeight:1.6 }}>After subscribing on Gumroad, you'll receive a unique license key by email. Enter it here to unlock your prompts.</div>
        <input value={key} onChange={e => { setKey(e.target.value); setStatus("idle"); }} onKeyDown={e => e.key==="Enter" && handleVerify()} placeholder="Enter your license key" style={{ width:"100%", background:"#030508", border:`1px solid ${status==="error"?"#ff4444":"#1a2030"}`, borderRadius:"4px", padding:"12px 14px", fontFamily:"'Space Mono',monospace", fontSize:"12px", color:"#8899bb", outline:"none", boxSizing:"border-box", marginBottom:"12px" }} />
        {status==="error" && <div style={{ fontSize:"11px", color:"#ff4444", fontFamily:"'Space Mono',monospace", marginBottom:"12px" }}>✗ Invalid key — check your Gumroad receipt email</div>}
        <div style={{ display:"flex", gap:"10px" }}>
          <button onClick={handleVerify} disabled={status==="loading"} style={{ flex:1, background:"linear-gradient(135deg,#00b4ff,#00ff90)", border:"none", color:"#030508", padding:"12px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"12px", fontWeight:"700", cursor:"pointer" }}>{status==="loading"?"VERIFYING...":"UNLOCK ACCESS →"}</button>
          <button onClick={onClose} style={{ padding:"12px 16px", background:"none", border:"1px solid #1e2535", color:"#445", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"11px", cursor:"pointer" }}>CANCEL</button>
        </div>
        <div style={{ marginTop:"20px", paddingTop:"16px", borderTop:"1px solid #0e1520", fontSize:"11px", color:"#334", fontFamily:"'Space Mono',monospace", textAlign:"center" }}>
          Don't have a key? → <a href="https://ogoina4.gumroad.com/l/qvcmgg" target="_blank" rel="noopener noreferrer" style={{ color:"#00b4ff", textDecoration:"none" }}>Subscribe to Pro</a> or <a href="https://ogoina4.gumroad.com/l/gveybd" target="_blank" rel="noopener noreferrer" style={{ color:"#ff6b35", textDecoration:"none" }}>Enterprise</a>
        </div>
      </div>
    </div>
  );
}

export default function App() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [activeTier, setActiveTier] = useState("All");
  const [search, setSearch] = useState("");
  const [selectedPrompt, setSelectedPrompt] = useState(null);
  const [email, setEmail] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const [counter, setCounter] = useState(0);
  const [userTier, setUserTier] = useState("free");
  const [showLicense, setShowLicense] = useState(false);

  useEffect(() => { const saved = localStorage.getItem("pv_tier"); if (saved) setUserTier(saved); }, []);
  useEffect(() => { const iv = setInterval(() => setCounter(c => c < 24891 ? c+Math.floor(Math.random()*37) : 24891), 30); return () => clearInterval(iv); }, []);

  const filtered = prompts.filter(p => {
    const matchCat = activeCategory==="All" || p.category===activeCategory;
    const matchTier = activeTier==="All" || p.tier===activeTier;
    const matchSearch = !search || p.title.toLowerCase().includes(search.toLowerCase()) || p.tags.some(t => t.includes(search.toLowerCase()));
    return matchCat && matchTier && matchSearch;
  });

  const freeCt = prompts.filter(p=>p.tier==="free").length;
  const proCt  = prompts.filter(p=>p.tier!=="enterprise").length;
  const tierBadgeColor = { free:"#00ff90", pro:"#00b4ff", enterprise:"#ff6b35" };

  return (
    <div style={{ fontFamily:"'Space Mono',monospace", background:"#030508", minHeight:"100vh", color:"#8899bb" }}>
      <link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@700;800;900&display=swap" rel="stylesheet" />
      <div style={{ position:"fixed", inset:0, pointerEvents:"none", zIndex:0, backgroundImage:`linear-gradient(rgba(0,180,255,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(0,180,255,0.03) 1px,transparent 1px)`, backgroundSize:"40px 40px" }} />
      <div style={{ position:"fixed", top:"-200px", left:"-200px", width:"500px", height:"500px", background:"radial-gradient(circle,rgba(0,180,255,0.04) 0%,transparent 70%)", pointerEvents:"none", zIndex:0 }} />
      <div style={{ position:"fixed", bottom:"-200px", right:"-100px", width:"400px", height:"400px", background:"radial-gradient(circle,rgba(0,255,144,0.03) 0%,transparent 70%)", pointerEvents:"none", zIndex:0 }} />
      <div style={{ position:"relative", zIndex:1 }}>
        <nav style={{ borderBottom:"1px solid #0e1520", padding:"0 32px", display:"flex", alignItems:"center", justifyContent:"space-between", height:"56px", background:"rgba(3,5,8,0.9)", backdropFilter:"blur(10px)", position:"sticky", top:0, zIndex:100 }}>
          <div style={{ display:"flex", alignItems:"center", gap:"10px" }}>
            <div style={{ width:"28px", height:"28px", background:"linear-gradient(135deg,#00b4ff,#00ff90)", borderRadius:"4px", display:"flex", alignItems:"center", justifyContent:"center", fontSize:"14px" }}>◈</div>
            <span style={{ fontFamily:"'Syne',sans-serif", fontWeight:"900", fontSize:"16px", color:"#e8eaf0", letterSpacing:"-0.02em" }}>PROMPT<span style={{ color:"#00b4ff" }}>VAULT</span></span>
          </div>
          <span style={{ fontSize:"10px", background:"#0a0a0a", border:"1px solid #333", color:"#00ff90", padding:"2px 8px", borderRadius:"2px", letterSpacing:"0.1em" }}>{counter.toLocaleString()} prompts used</span>
          <div style={{ display:"flex", gap:"12px", alignItems:"center" }}>
            <span onClick={() => document.getElementById("library").scrollIntoView({ behavior:"smooth" })} style={{ fontSize:"12px", color:"#6677aa", cursor:"pointer" }}>Library</span>
            <span onClick={() => document.getElementById("pricing").scrollIntoView({ behavior:"smooth" })} style={{ fontSize:"12px", color:"#6677aa", cursor:"pointer" }}>Pricing</span>
            {userTier!=="free" ? (
              <span style={{ fontSize:"10px", background:`${tierBadgeColor[userTier]}18`, border:`1px solid ${tierBadgeColor[userTier]}`, color:tierBadgeColor[userTier], padding:"5px 12px", borderRadius:"4px", letterSpacing:"0.05em" }}>✓ {userTier.toUpperCase()}</span>
            ) : (
              <button onClick={() => setShowLicense(true)} style={{ background:"linear-gradient(135deg,#00b4ff,#00ff90)", border:"none", color:"#030508", padding:"7px 16px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"11px", fontWeight:"700", cursor:"pointer", letterSpacing:"0.05em" }}>UNLOCK ACCESS →</button>
            )}
          </div>
        </nav>

        <div style={{ padding:"80px 32px 60px", maxWidth:"900px", margin:"0 auto", textAlign:"center" }}>
          <div style={{ display:"inline-flex", alignItems:"center", gap:"8px", border:"1px solid #0e1a28", borderRadius:"100px", padding:"6px 14px", fontSize:"11px", marginBottom:"32px", background:"#00b4ff08", color:"#00b4ff" }}>
            <span style={{ width:"6px", height:"6px", borderRadius:"50%", background:"#00ff90", display:"inline-block", animation:"pulse 2s infinite" }} />
            v3.0 — {prompts.length} prompts across {categories.length-1} industries
          </div>
          <h1 style={{ fontFamily:"'Syne',sans-serif", fontSize:"clamp(42px,8vw,80px)", fontWeight:"900", lineHeight:0.95, letterSpacing:"-0.03em", color:"#e8eaf0", marginBottom:"24px" }}>
            <GlitchText text="Battle-tested" /><br />
            <span style={{ background:"linear-gradient(135deg,#00b4ff 0%,#00ff90 100%)", WebkitBackgroundClip:"text", WebkitTextFillColor:"transparent" }}>AI prompts</span><br />
            that actually work.
          </h1>
          <p style={{ fontSize:"16px", color:"#5a6a7a", lineHeight:1.7, maxWidth:"520px", margin:"0 auto 40px" }}>Stop writing prompts from scratch. Access a curated library of expert-crafted prompts for legal, finance, marketing, engineering, and more.</p>
          <div style={{ display:"flex", gap:"12px", justifyContent:"center", marginBottom:"40px" }}>
            <button onClick={() => document.getElementById("library").scrollIntoView({ behavior:"smooth" })} style={{ background:"linear-gradient(135deg,#00b4ff,#00ff90)", border:"none", color:"#030508", padding:"12px 28px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"12px", fontWeight:"700", cursor:"pointer", letterSpacing:"0.05em" }}>BROWSE PROMPTS →</button>
            <button onClick={() => document.getElementById("pricing").scrollIntoView({ behavior:"smooth" })} style={{ background:"transparent", border:"1px solid #2a3545", color:"#8899bb", padding:"12px 28px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"12px", cursor:"pointer", letterSpacing:"0.05em" }}>VIEW PRICING</button>
          </div>
          <div style={{ display:"flex", gap:"12px", justifyContent:"center", flexWrap:"wrap" }}>
            {[{ label:`${prompts.length}`, sub:"Prompts" }, { label:"$0", sub:"To start" }, { label:`${categories.length-1}`, sub:"Industries" }, { label:"24k+", sub:"Users" }].map(stat => (
              <div key={stat.label} style={{ background:"#080c10", border:"1px solid #0e1520", borderRadius:"8px", padding:"16px 24px", textAlign:"center" }}>
                <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"28px", fontWeight:"900", color:"#e8eaf0" }}>{stat.label}</div>
                <div style={{ fontSize:"11px", color:"#445" }}>{stat.sub}</div>
              </div>
            ))}
          </div>
        </div>

        <div id="library" style={{ maxWidth:"1100px", margin:"0 auto", padding:"0 32px 80px" }}>
          <div style={{ borderBottom:"1px solid #0e1520", marginBottom:"32px", paddingBottom:"16px", display:"flex", justifyContent:"space-between", alignItems:"flex-end" }}>
            <div>
              <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"11px", letterSpacing:"0.2em", color:"#00b4ff", marginBottom:"4px" }}>// PROMPT LIBRARY</div>
              <div style={{ fontSize:"22px", fontFamily:"'Syne',sans-serif", fontWeight:"800", color:"#e8eaf0" }}>Browse the vault</div>
            </div>
            {userTier==="free" && <button onClick={() => setShowLicense(true)} style={{ background:"transparent", border:"1px solid #00b4ff", color:"#00b4ff", padding:"8px 16px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"10px", cursor:"pointer", letterSpacing:"0.05em" }}>🔑 ENTER UNLOCK CODE</button>}
          </div>

          <div style={{ display:"flex", gap:"10px", marginBottom:"24px", flexWrap:"wrap", alignItems:"center" }}>
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search prompts..." style={{ background:"#080c10", border:"1px solid #1a2030", borderRadius:"4px", padding:"8px 14px", fontFamily:"'Space Mono',monospace", fontSize:"12px", color:"#8899bb", outline:"none", width:"190px" }} />
            <div style={{ display:"flex", gap:"5px", flexWrap:"wrap" }}>
              {categories.map(cat => <button key={cat} onClick={() => setActiveCategory(cat)} style={{ background:activeCategory===cat?"#00b4ff15":"transparent", border:`1px solid ${activeCategory===cat?"#00b4ff":"#1a2030"}`, color:activeCategory===cat?"#00b4ff":"#445", padding:"6px 10px", borderRadius:"4px", cursor:"pointer", fontFamily:"'Space Mono',monospace", fontSize:"9px", letterSpacing:"0.05em" }}>{cat==="All"?"ALL":`${categoryIcons[cat]||""} ${cat.toUpperCase()}`}</button>)}
            </div>
            <div style={{ display:"flex", gap:"6px", marginLeft:"auto" }}>
              {tiers.map(t => { const tc = t==="free"?"#00ff90":t==="pro"?"#00b4ff":t==="enterprise"?"#ff6b35":"#e8eaf0"; const isActive = activeTier===t; return <button key={t} onClick={() => setActiveTier(t)} style={{ background:isActive?`${tc}18`:"transparent", border:`1px solid ${isActive?tc:"#2a3545"}`, color:isActive?tc:"#556677", padding:"6px 12px", borderRadius:"4px", cursor:"pointer", fontFamily:"'Space Mono',monospace", fontSize:"10px", textTransform:"uppercase", transition:"all 0.15s", fontWeight:isActive?"700":"400" }}>{t}</button>; })}
            </div>
          </div>

          {userTier==="free" && (
            <div style={{ background:"#00b4ff08", border:"1px solid #00b4ff22", borderRadius:"6px", padding:"12px 16px", marginBottom:"20px", display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <span style={{ fontSize:"11px", color:"#5577aa", fontFamily:"'Space Mono',monospace" }}>◌ FREE TIER — {freeCt} prompts unlocked · {prompts.length-freeCt} locked</span>
              <button onClick={() => setShowLicense(true)} style={{ background:"none", border:"1px solid #00b4ff", color:"#00b4ff", padding:"5px 12px", borderRadius:"3px", fontFamily:"'Space Mono',monospace", fontSize:"9px", cursor:"pointer", letterSpacing:"0.08em" }}>UNLOCK ALL →</button>
            </div>
          )}

          <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))", gap:"16px" }}>
            {filtered.map(p => <PromptCard key={p.id} prompt={p} userTier={userTier} onClick={setSelectedPrompt} onUnlock={() => setShowLicense(true)} />)}
          </div>
          {filtered.length===0 && <div style={{ textAlign:"center", padding:"60px", color:"#334", fontFamily:"'Space Mono',monospace", fontSize:"12px" }}>NO PROMPTS FOUND // TRY ADJUSTING FILTERS</div>}
        </div>

        <div id="pricing" style={{ borderTop:"1px solid #0e1520", padding:"80px 32px", maxWidth:"1000px", margin:"0 auto" }}>
          <div style={{ textAlign:"center", marginBottom:"48px" }}>
            <div style={{ fontSize:"11px", letterSpacing:"0.2em", color:"#00b4ff", marginBottom:"8px", fontFamily:"'Space Mono',monospace" }}>// PRICING</div>
            <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"32px", fontWeight:"900", color:"#e8eaf0" }}>Start free. Scale when ready.</div>
          </div>
          <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))", gap:"16px" }}>
            {[
              { name:"FREE", price:"$0", period:"/forever", color:"#00ff90", features:[`${freeCt} free prompts`,`${categories.length-1} categories covered`,"Copy & use instantly","No credit card needed"], cta:"BROWSE FREE →", href:"#library" },
              { name:"PRO", price:"$29", period:"/month", color:"#00b4ff", highlight:true, features:[`${proCt} premium prompts`,`${freeCt} free + ${proCt-freeCt} pro prompts`,"All industries covered","New prompts added weekly","Priority support"], cta:"GO PRO →", href:"https://ogoina4.gumroad.com/l/qvcmgg" },
              { name:"ENTERPRISE", price:"$199", period:"/month", color:"#ff6b35", features:[`All ${prompts.length} prompts unlocked`,"Custom prompt creation","10 team seats","API access","Dedicated support"], cta:"GET ENTERPRISE →", href:"https://ogoina4.gumroad.com/l/gveybd" },
            ].map(plan => (
              <div key={plan.name} style={{ background:plan.highlight?"#0a0f18":"#080c10", border:`1px solid ${plan.highlight?plan.color:"#1a2030"}`, borderRadius:"10px", padding:"28px", position:"relative", overflow:"hidden", boxShadow:plan.highlight?`0 0 40px ${plan.color}22`:"none" }}>
                {plan.highlight && <div style={{ position:"absolute", top:"12px", right:"12px", background:"#00b4ff15", border:"1px solid #00b4ff", color:"#00b4ff", fontSize:"9px", padding:"3px 8px", borderRadius:"2px", fontFamily:"'Space Mono',monospace", letterSpacing:"0.1em" }}>POPULAR</div>}
                <div style={{ fontSize:"11px", color:plan.color, letterSpacing:"0.15em", marginBottom:"12px" }}>{plan.name}</div>
                <div style={{ marginBottom:"24px" }}><span style={{ fontFamily:"'Syne',sans-serif", fontSize:"40px", fontWeight:"900", color:"#e8eaf0" }}>{plan.price}</span><span style={{ fontSize:"12px", color:"#445" }}>{plan.period}</span></div>
                <div style={{ marginBottom:"24px" }}>{plan.features.map(f => <div key={f} style={{ display:"flex", gap:"10px", marginBottom:"10px", fontSize:"12px", color:"#6677aa" }}><span style={{ color:plan.color }}>›</span> {f}</div>)}</div>
                <a href={plan.href} target={plan.href.startsWith("http")?"_blank":"_self"} rel="noopener noreferrer" style={{ display:"block", width:"100%", padding:"12px", background:plan.highlight?"linear-gradient(135deg,#00b4ff,#00ff90)":"transparent", border:plan.highlight?"none":`1px solid ${plan.color}`, color:plan.highlight?"#030508":plan.color, borderRadius:"4px", cursor:"pointer", fontFamily:"'Space Mono',monospace", fontSize:"12px", fontWeight:"700", letterSpacing:"0.05em", textAlign:"center", textDecoration:"none", boxSizing:"border-box" }}>{plan.cta}</a>
                {plan.name!=="FREE" && <div style={{ marginTop:"10px", textAlign:"center" }}><span onClick={() => setShowLicense(true)} style={{ fontSize:"10px", color:"#334", fontFamily:"'Space Mono',monospace", cursor:"pointer", textDecoration:"underline" }}>Already subscribed? Enter unlock code</span></div>}
              </div>
            ))}
          </div>
        </div>

        <div style={{ borderTop:"1px solid #0e1520", padding:"80px 32px", textAlign:"center" }}>
          <div style={{ maxWidth:"500px", margin:"0 auto", background:"#080c10", border:"1px solid #1a2030", borderRadius:"12px", padding:"40px", position:"relative", overflow:"hidden" }}>
            <div style={{ position:"absolute", top:0, left:0, right:0, height:"1px", background:"linear-gradient(90deg,transparent,#00b4ff,#00ff90,transparent)" }} />
            <div style={{ fontSize:"11px", color:"#00b4ff", letterSpacing:"0.2em", marginBottom:"12px" }}>// EARLY ACCESS</div>
            <div style={{ fontFamily:"'Syne',sans-serif", fontSize:"22px", fontWeight:"900", color:"#e8eaf0", marginBottom:"8px" }}>Get {freeCt} free prompts instantly</div>
            <div style={{ fontSize:"12px", color:"#445", marginBottom:"24px" }}>No credit card. No spam. Just prompts that work.</div>
            {subscribed ? (
              <div style={{ color:"#00ff90", fontFamily:"'Space Mono',monospace", fontSize:"13px" }}>✓ ACCESS GRANTED — CHECK YOUR EMAIL</div>
            ) : (
              <div>
                <iframe name="mc_embed_iframe" style={{ display:"none" }} title="mc" />
                <form action="https://gmail.us2.list-manage.com/subscribe/post?u=13f674f36946617471a726a61&id=d56b3d028a&f_id=00ccc7e1f0" method="post" target="mc_embed_iframe" onSubmit={e => { if (email) { setSubscribed(true); } else { e.preventDefault(); } }} style={{ display:"flex", gap:"8px" }}>
                  <input type="email" name="EMAIL" value={email} onChange={e => setEmail(e.target.value)} placeholder="your@email.com" required style={{ flex:1, background:"#030508", border:"1px solid #1a2030", borderRadius:"4px", padding:"10px 14px", fontFamily:"'Space Mono',monospace", fontSize:"12px", color:"#8899bb", outline:"none" }} />
                  <div style={{ position:"absolute", left:"-5000px" }} aria-hidden="true"><input type="text" name="b_13f674f36946617471a726a61_d56b3d028a" tabIndex="-1" defaultValue="" readOnly /></div>
                  <button type="submit" style={{ background:"linear-gradient(135deg,#00b4ff,#00ff90)", border:"none", color:"#030508", padding:"10px 20px", borderRadius:"4px", fontFamily:"'Space Mono',monospace", fontSize:"11px", fontWeight:"700", cursor:"pointer", whiteSpace:"nowrap" }}>GET ACCESS</button>
                </form>
              </div>
            )}
          </div>
        </div>

        <div style={{ borderTop:"1px solid #0e1520", padding:"24px 32px", display:"flex", justifyContent:"space-between", alignItems:"center", fontSize:"11px", color:"#2a3040" }}>
          <span style={{ fontFamily:"'Syne',sans-serif", fontWeight:"900", color:"#1e2535" }}>PROMPT<span style={{ color:"#1a2f40" }}>VAULT</span></span>
          <span style={{ fontFamily:"'Space Mono',monospace" }}>© 2026 — BUILT WITH AI</span>
        </div>
      </div>

      {selectedPrompt && <Modal prompt={selectedPrompt} onClose={() => setSelectedPrompt(null)} />}
      {showLicense && <LicenseModal onClose={() => setShowLicense(false)} onVerified={t => setUserTier(t)} />}
      <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:#030508}::-webkit-scrollbar-thumb{background:#1a2535}`}</style>
    </div>
  );
}